server:
  port: 8081
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: freaky
freaky-slow-service:
  random-url: http://localhost:8082/random
  randoms-url: http://localhost:8082/random/{limit}